### ISSUE TITLE
TypeError: 'str' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by GrahamCobb** [Ferroin/btrfs-subv-backup#1]
Trying to run, on a fairly standard Debian buster system, I get the following error:

Traceback (most recent call last):
  File "/usr/lib/python3.5/argparse.py", line 1349, in add_argument
    self._get_formatter()._format_args(action, None)
  File "/usr/lib/python3.5/argparse.py", line 596, in _format_args
    formats = ['%s' for _ in range(action.nargs)]
TypeError: 'str' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./btrfs-subv-backup.py", line 357, in <module>
    sys.exit(main())
  File "./btrfs-subv-backup.py", line 331, in main
    args = parse_args()
  File "./btrfs-subv-backup.py", line 314, in parse_args
    help='Select a particular restore method.  Available options are reflink and copy.')
  File "/usr/lib/python3.5/argparse.py", line 1351, in add_argument
    raise ValueError("length of metavar tuple does not match nargs")
ValueError: length of metavar tuple does not match nargs

**Comment by GrahamCobb** [comment]
And (fairly unsurprisingly) I get the same error when trying to run on my other btrfs disk.

**Comment by Ferroin** [comment]
Well, that's a bit embarrassing, I forgot to check the script as a whole instead of checking the functions from an interactive Python session.  Fix pushed as 032e9d8dfd7f0b609b6671a225bdf6753762ad3f.

**Comment by GrahamCobb** [comment]
I can confirm that the new version doesn't have the problem. It is still running though. Is the time dependent on the number of subvolumes or the number of files on the disk?

**Comment by Ferroin** [comment]
It uses os.walk() to traverse the entire directory structure, but it only looks at directories, so unless I'm doing the math wrong it should be proportionate only to the number of directories.  That said, it might not be pruning mount points properly (it's not supposed to cross actual mount points, but I'm not 100% certain it's matching them correctly in all cases), and if that's the case and it gets run on /, it will likely take a very long time to complete because of `/proc` and `/sys`.

**Comment by GrahamCobb** [comment]
Thanks. I am not running on / (or any other mount traversals) but the filesystem does contain a **lot** of snapshots of subvolumes many of which have **lots** of directories. So it will take a long time. Even just walking all the directories on the disk will probably take a day I suspect.

I had assumed that in the backup phase it just listed the subvolumes and saved the information in a convenient to use format. And if I ever needed to restore, I wouldn't be handling all those snapshots (I don't back them up in my last ditch, non-btrfs backups). Oh well.

**Comment by Ferroin** [comment]
Adding exclude patterns to handle things like ignoring snapshots is on my list of things to do, so eventually it should be significantly faster, I just haven't had time to add it yet.

As far as crawling the tree, that's mostly because it's really hard to figure out reliably and efficiently what's under a given mount point that's a subvolume just based on `btrfs subvolume list` and the contents of `/proc/mounts` (doing it sanely would require an in-memory database, which I consider to be more work than it's worth right now).  It also makes it possible to run as a non-root user and save the information (which makes it a bit easier to integrate with some backup systems).

**Comment by Ferroin** [comment]
OK, turns out that mount points weren't being excluded correctly, that's fixed now, and I've added an option to exclude paths from the search based on shell-style glob patterns.

Given that the original issue is resolved, and that the handful of other things brought up here are fixed too, I'm closing this.
